name: node-hello-application
servicename: node-hello-service
replicas: 1

image:
  name: vishaldixit0611/node-hello:latest
  pullPolicy: Always
  secrets: dockerhub-creds


ports:
  - name: http
    port: 3000

serviceEnabled: true

serviceType: LoadBalancer

