apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Nodejs
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/Vishal-Dixit-0611/Nodejs-ArgoCD.git'
    path: helmchart
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc
    namespace: nodejs
  project: nodejs-hello-argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
