apiVersion: apps/v1
kind: Deployment
metadata:
  name: Nodejs-Deployment
  labels:
    app: Nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Nodejs
  template:
    metadata:
      labels:
        app: Nodejs
    spec:
      containers:
      - name: Nodejs-hello
        image: vishaldixit0611/node-hello:latest
        ports:
        - containerPort: 3000

